"""app.services.pedido_history — phase 4 timeline for /pedidos/{id}.

Build a coherent timeline of everything that happened to a pedido:
  - Status transitions (from AuditLog with action like write.pedido.status)
  - Sale events (fulfilled → which Sale row + total)
  - Loyalty events (points earned/redeemed from LoyaltyTransaction)
  - Create event (from AuditLog write.pedido.create)

Used by:
- pedido_detail handler to render a timeline + recent pedidos for
  the customer
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import select

from app.rms.models import (
    AuditLog,
    Customer,
    LoyaltyTransaction,
    Pedido,
    PedidoEvent,
    Sale,
)

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


@dataclass
class TimelineEvent:
    """One entry in a pedido's timeline."""

    when: datetime
    kind: str  # 'created' | 'status' | 'fulfilled' | 'loyalty' | 'cancelled'
    label: str  # human-readable label
    detail: str | None = None
    actor: str | None = None  # username / user_id

    def to_dict(self) -> dict:
        return {
            "when": self.when.isoformat() if self.when else None,
            "kind": self.kind,
            "label": self.label,
            "detail": self.detail,
            "actor": self.actor,
        }


def build_pedido_timeline(session: Session, pedido: Pedido) -> list[TimelineEvent]:
    """Build the chronological event list for one pedido.

    Combines AuditLog rows (status transitions, creates, edits) with
    Sale rows (fulfillment) and LoyaltyTransaction rows (point events).
    Returns the events sorted by occurred_at ascending.
    """
    events: list[TimelineEvent] = []

    # Audit rows for this pedido
    audit_rows = session.execute(
        select(AuditLog)
        .where(
            AuditLog.target_type == "pedido",
            AuditLog.target_id == str(pedido.id),
        )
        .order_by(AuditLog.occurred_at)
    ).scalars().all()

    for row in audit_rows:
        if row.action == "write.pedido.create":
            events.append(TimelineEvent(
                when=row.occurred_at,
                kind="created",
                label="Pedido creado",
                actor=row.user_id,
            ))
        elif row.action == "write.pedido.status":
            new_status = (row.detail or {}).get("new_status", "?")
            old_status = (row.detail or {}).get("old_status", "?")
            events.append(TimelineEvent(
                when=row.occurred_at,
                kind="status",
                label=f"{old_status} → {new_status}",
                detail=(row.detail or {}).get("reason"),
                actor=row.user_id,
            ))
        elif row.action == "write.pedido.duplicate":
            events.append(TimelineEvent(
                when=row.occurred_at,
                kind="duplicate",
                label=f"Duplicado de pedido #{(row.detail or {}).get('original_id', '?')}",
                actor=row.user_id,
            ))

    # Sale rows generated by this pedido (Migration 076 unblocked this).
    # Pedido.fulfilled_sale_id only points at the FIRST sale from a multi-
    # line fulfillment; we use the collection relationship to grab them all.
    for sale in pedido.sales:
        events.append(TimelineEvent(
            when=sale.sold_at,
            kind="fulfilled",
            label=f"Venta #{sale.id}" + (" (primer)" if sale.id == pedido.fulfilled_sale_id else ""),
            detail=f"Gs. {int(sale.qty * sale.unit_price_gs):,}".replace(",", "."),
            actor=sale.user_id if hasattr(sale, 'user_id') else None,
        ))

    # Loyalty transactions for this customer around this pedido's lifetime
    if pedido.customer_id:
        lt_rows = session.execute(
            select(LoyaltyTransaction)
            .where(
                LoyaltyTransaction.customer_id == pedido.customer_id,
                LoyaltyTransaction.recorded_at >= pedido.created_at,
            )
            .order_by(LoyaltyTransaction.recorded_at)
        ).scalars().all()
        for lt in lt_rows:
            sign = "+" if lt.points_delta > 0 else ""
            events.append(TimelineEvent(
                when=lt.recorded_at,
                kind="loyalty",
                label=f"Puntos {sign}{lt.points_delta}",
                detail=lt.reason,
            ))

    # Phase 11 — PedidoEvent rows (per-pedido edit log). These are the
    # higher-fidelity complement to AuditLog: created, line_added,
    # status_change, etc. The kind is the event_type directly.
    pe_rows = session.execute(
        select(PedidoEvent)
        .where(PedidoEvent.pedido_id == pedido.id)
        .order_by(PedidoEvent.ts)
    ).scalars().all()
    for pe in pe_rows:
        events.append(TimelineEvent(
            when=pe.ts,
            kind="event",
            label=_label_for_event_type(pe.event_type),
            detail=_detail_for_event(pe.event_type, pe.payload_json),
            actor=pe.actor,
        ))

    # Sort by occurred_at ascending (None last). Use a key that handles None.
    events.sort(key=lambda e: e.when or datetime.min)
    return events


def _label_for_event_type(event_type: str) -> str:
    """Human-readable Spanish label for a PedidoEvent.event_type."""
    return {
        "created": "Pedido creado",
        "status_change": "Estado cambiado",
        "line_added": "Línea añadida",
        "line_removed": "Línea eliminada",
        "line_qty_changed": "Cantidad editada",
        "line_price_changed": "Precio editado",
        "note_edited": "Notas editadas",
        "address_changed": "Dirección cambiada",
        "window_changed": "Ventana de entrega cambiada",
        "customer_changed": "Cliente reasignado",
        "payment_intent_set": "Método de pago cambiado",
        "cancelled": "Pedido cancelado",
        "duplicated": "Duplicado",
    }.get(event_type, event_type)


def _detail_for_event(event_type: str, payload: dict | None) -> str | None:
    """Render the payload diff as a one-line human detail string."""
    if not payload:
        return None
    if event_type == "status_change":
        return f"{payload.get('from', '?')} → {payload.get('to', '?')}"
    if event_type == "line_added":
        return f"producto #{payload.get('product_id')} × {payload.get('qty')}"
    if event_type == "cancelled":
        return f"motivo: {payload.get('reason', '?')}"
    if event_type == "address_changed":
        addr = payload.get("address_text", "")
        return (addr[:60] + "…") if len(str(addr)) > 60 else addr
    if event_type == "window_changed":
        return f"{payload.get('from', '?')} → {payload.get('to', '?')}"
    # Default: compact JSON
    import json
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


@dataclass
class CustomerPedidoSummary:
    """Compact representation of a pedido for the customer's history list."""

    id: int
    status: str
    promised_date: str | None
    total_gs: int
    line_count: int
    is_current: bool = False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "status": self.status,
            "promised_date": self.promised_date,
            "total_gs": self.total_gs,
            "line_count": self.line_count,
            "is_current": self.is_current,
        }


def customer_recent_pedidos(
    session: Session,
    customer_id: int,
    *,
    limit: int = 8,
    exclude_pedido_id: int | None = None,
) -> list[CustomerPedidoSummary]:
    """Return the customer's most-recent pedidos as compact summaries.

    Useful for showing "Otros pedidos de este cliente" on the detail page
    so the operator can quickly jump to history.
    """
    q = (
        select(Pedido)
        .where(Pedido.customer_id == customer_id)
        .order_by(Pedido.promised_date.desc(), Pedido.id.desc())
        .limit(limit)
    )
    if exclude_pedido_id is not None:
        # Use a NOT-EQUAL filter via Python (excludes the current pedido)
        pedidos = [p for p in session.execute(q).scalars().all() if p.id != exclude_pedido_id][:limit]
    else:
        pedidos = session.execute(q).scalars().all()

    out: list[CustomerPedidoSummary] = []
    for p in pedidos:
        total = sum(int(ln.qty * ln.unit_price_gs) for ln in p.lines)
        out.append(CustomerPedidoSummary(
            id=p.id,
            status=p.status,
            promised_date=p.promised_date.isoformat() if p.promised_date else None,
            total_gs=total,
            line_count=len(p.lines),
        ))
    return out
