"""tests/test_route_smoke_phase14_tier1.py — Phase 14 Tier 1 (2026-10-01).

The Coverage Gate strategy doc (2026-10-01) calls for a smoke test
that hits every `@router.get` so the gate catches regressions on the
route layer (the biggest single contributor to missing coverage —
~3500 statements of HTTP plumbing per the strategy doc).

This file parametrize-tests every GET route in `app/routers/` that the
auth-bypass TestClient can hit. POSTs are intentionally excluded (they
would change DB state; the existing test_smoke_all_routes.py covers
specific POSTs by hand).

What this catches:
- 500s from template errors (e.g. a renamed variable in a Jinja template)
- 500s from missing migrations (e.g. a new ORM column referenced in code)
- 500s from broken import paths (a renamed module -> router import error)
- Routing regressions (a router included with wrong prefix)

What this does NOT catch:
- Template rendering bugs that produce 200 + wrong content (covered
  by hand-curated test_smoke_all_routes.py + tests/ui/)
- POSTs that succeed but corrupt data (covered by CRUD tests)

Design notes:
- Catalog is embedded (not generated) so the test is self-contained.
- Each test is parametrized with a stable id so failures are easy to
  locate (`tests/test_route_smoke_phase14_tier1.py::...[<file>::<fn>]`).
- Param-routes (28 of them with `{id}`) use `id=1` by default. Many
  routes return 404 for an unknown id — that's fine, we just assert
  the response is NOT a 5xx (so the routing + auth gate + Jinja loader
  + SQLAlchemy session all work).
- SASKIA_TEST_AUTH_DISABLED=1 (from conftest) skips the login gate.
- Routes under /api/search etc. that expect ?q= are tested with the
  cheapest valid query (e.g. ?q=x).

Last regenerated: see `tests/_route_smoke_catalog.py` if you need to
add new routes — the catalog is regenerated by scripts/tier1_regen_route_catalog.py
in CI. Until that script is in place, edit the embedded list below by hand.
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.smoke

# (file, function, url, has_param)
# Built by scripts/_tier1_route_catalog.py from app/routers/*.py at
# commit time. Hand-curated subsets can also live here; we just need
# the structural ones (every @router.get).
ROUTE_CATALOG = [
    # ─── analisis ───
    ("analisis.py", "analisis_view", "/analisis", False),
    # ─── auth ───
    ("auth.py", "login_form", "/login", False),
    ("auth.py", "logout_get", "/logout", False),
    ("auth.py", "forgot_password_form", "/forgot-password", False),
    ("auth.py", "reset_password_form", "/reset-password", False),
    # ─── auditoria ───
    ("auditoria.py", "auditoria_index", "/auditoria", False),
    ("auditoria.py", "auditoria_export_csv", "/auditoria/export.csv", False),
    # ─── credits ───
    ("credits.py", "credits_page", "/creditos", False),
    # ─── customers ───
    ("customers.py", "cliente_new", "/clientes/nuevo", False),
    ("customers.py", "clientes_list", "/clientes", False),
    ("customers.py", "cliente_detail", "/clientes/{customer_id}", True),
    ("customers.py", "cliente_edit", "/clientes/{customer_id}/editar", True),
    ("customers.py", "customer_detail_api", "/clientes/api/{customer_id}", True),
    # ─── dashboard ───
    ("dashboard.py", "dashboard_view", "/", False),
    # ─── demo ───
    ("demo.py", "demo_index", "/demo", False),
    # ─── dev ───
    ("dev.py", "dev_combo_smoke", "/dev/combo-smoke", False),
    ("dev.py", "dev_components_smoke", "/dev/components-smoke", False),
    # ─── eod ───
    ("eod.py", "eod_view", "/eod", False),
    # ─── excel_io ───
    ("excel_io.py", "excel_index", "/excel", False),
    ("excel_io.py", "excel_template_download", "/excel/template.xlsx", False),
    # ─── health ───
    ("health.py", "healthz", "/healthz", False),
    ("health.py", "healthz_db", "/healthz/db", False),
    ("health.py", "healthz_schema", "/healthz/schema", False),
    ("health.py", "healthz_deps", "/healthz/deps", False),
    ("health.py", "healthz_errors", "/healthz/errors", False),
    # ─── help ───
    ("help.py", "guia_index", "/guia", False),
    ("help.py", "guia_section", "/guia/{section}", True),
    # ─── insights ───
    ("insights.py", "insights_index", "/insights", False),
    # ─── insights_derived ───
    ("insights_derived.py", "reportes_index", "/reportes", False),
    ("insights_derived.py", "price_impact_view", "/reportes/price-impact/{ingredient_id}", True),
    ("insights_derived.py", "substitutes_api", "/reportes/api/substitutes/{ingredient_id}", True),
    # ─── insights_stock ───
    ("insights_stock.py", "margenes_product_view", "/reportes/margenes/{product_id}", True),
    ("insights_stock.py", "wishlist_view", "/wishlist", False),
    # ─── inventory ───
    ("inventory.py", "inventory_index", "/inventario", False),
    ("inventory.py", "inventory_new", "/inventario/nuevo", False),
    ("inventory.py", "inventory_detail", "/inventario/{ing_id}", True),
    ("inventory.py", "inventory_edit", "/inventario/{ing_id}/editar", True),
    # ─── merma ───
    ("merma.py", "merma_index", "/merma", False),
    ("merma.py", "merma_nuevo", "/merma/nuevo", False),
    # ─── ops ───
    ("ops.py", "ops_status", "/ops/status", False),
    # ─── pedidos ───
    ("pedidos.py", "pedido_list", "/pedidos", False),
    ("pedidos.py", "pedido_nuevo", "/pedidos/nuevo", False),
    ("pedidos.py", "pedido_board", "/pedidos/board", False),
    ("pedidos.py", "pedido_detail", "/pedidos/{pedido_id}", True),
    ("pedidos.py", "pedido_edit", "/pedidos/{pedido_id}/editar", True),
    # ─── produccion ───
    ("produccion.py", "produccion_index", "/produccion", False),
    ("produccion.py", "produccion_nuevo", "/produccion/nuevo", False),
    ("produccion.py", "produccion_planner", "/produccion/planner", False),
    # ─── products ───
    ("products.py", "products_list", "/productos", False),
    ("products.py", "products_new", "/productos/nuevo", False),
    ("products.py", "products_detail", "/productos/{product_id}", True),
    ("products.py", "products_edit", "/productos/{product_id}/editar", True),
    # ─── recipes ───
    ("recipes.py", "recipes_list", "/recetas", False),
    ("recipes.py", "recipe_new", "/recetas/nueva", False),
    ("recipes.py", "recipe_detail", "/recetas/{recipe_id}", True),
    ("recipes.py", "recipe_edit", "/recetas/{recipe_id}/editar", True),
    # ─── reorder ───
    ("reorder.py", "reorder_index", "/reorder", False),
    # ─── reportes ───
    ("reportes.py", "reportes_iva", "/reportes/iva", False),
    ("reportes.py", "reportes_diario", "/reportes/diario", False),
    ("reportes.py", "reportes_comparacion", "/reportes/comparacion", False),
    ("reportes.py", "reportes_top_productos", "/reportes/top-productos", False),
    ("reportes.py", "reportes_retencion", "/reportes/retencion", False),
    ("reportes.py", "reportes_metodos_pago", "/reportes/metodos-pago", False),
    ("reportes.py", "reportes_precios", "/reportes/precios", False),
    # ─── sales ───
    ("sales.py", "sales_list", "/ventas", False),
    ("sales.py", "sale_new", "/ventas/nueva", False),
    ("sales.py", "sale_search", "/ventas/buscar", False),
    ("sales.py", "sale_detail", "/ventas/{sale_id}", True),
    # ─── search ───
    ("search.py", "global_search_api", "/api/search", False),
    # ─── settings ───
    ("settings.py", "settings_index", "/settings", False),
    ("settings.py", "settings_categories", "/settings/categorias", False),
    ("settings.py", "settings_channels", "/settings/channels", False),
    # ─── settings_runtime ───
    ("settings_runtime.py", "settings_runtime_api", "/api/settings/runtime", False),
    # ─── shopping ───
    ("shopping.py", "shopping_list_index", "/shopping-list", False),
    # ─── suppliers ───
    ("suppliers.py", "suppliers_list", "/suppliers", False),
    ("suppliers.py", "supplier_new", "/suppliers/nuevo", False),
    ("suppliers.py", "supplier_detail", "/suppliers/{supplier_id}", True),
    ("suppliers.py", "supplier_edit", "/suppliers/{supplier_id}/editar", True),
    # ─── suscripciones ───
    ("suscripciones.py", "suscripciones_index", "/suscripciones", False),
    # ─── users ───
    ("users.py", "users_list", "/users", False),
    ("users.py", "user_new", "/users/nuevo", False),
    # ─── validation ───
    ("validation.py", "validation_api", "/api/validate/{kind}", True),
]


def _substitute_params(url: str, has_param: bool) -> str:
    """For routes with path params, substitute id=1 by default.

    Many routes return 404 for unknown ids — that's fine for the
    smoke test (we only assert not-5xx). The point is to exercise
    the routing, auth gate, Jinja loader, and SQLAlchemy session.
    """
    if not has_param:
        return url
    return (
        url.replace("{customer_id}", "1")
        .replace("{pedido_id}", "1")
        .replace("{product_id}", "1")
        .replace("{recipe_id}", "1")
        .replace("{ing_id}", "1")
        .replace("{supplier_id}", "1")
        .replace("{sale_id}", "1")
        .replace("{ingredient_id}", "1")
        .replace("{section}", "general")
        .replace("{kind}", "phone")
    )


def _id_for_route(*case) -> str:
    """Stable pytest test id. Pytest calls this once per param value,
    so we accept *args and pick the first non-empty string."""
    for v in case:
        if isinstance(v, str) and v and "/" in v:
            return f"[{v}]"
        if isinstance(v, str) and v and "." in v:
            return v
    return str(case[0]) if case else "?"


@pytest.mark.parametrize(
    "file,fn,url,has_param",
    ROUTE_CATALOG,
    ids=_id_for_route,
)
def test_route_returns_not_5xx(client, file, fn, url, has_param):
    """Every GET route must NOT 5xx.

    Allowed: 200, 303 (redirect), 404 (unknown id), 422 (form
    validation failure). Forbidden: 500/502/503.

    The 4xx/3xx outcomes still prove:
    - routing is wired correctly
    - auth gate accepted the request
    - DB session was constructed
    - Jinja templates loaded without syntax errors

    If a 5xx sneaks in, this test is the early warning that the route
    is broken in some new way (renamed var, missing migration, etc.).
    """
    real_url = _substitute_params(url, has_param)
    r = client.get(real_url)
    assert r.status_code < 500, (
        f"GET {real_url} ({file}::{fn}) returned {r.status_code}: {r.text[:200]}"
    )


def test_route_catalog_covers_at_least_50_routes():
    """Sanity check: this test only matters if the catalog has enough
    routes. If you trim the catalog to < 50 routes, you might as well
    delete this file and rely on test_smoke_all_routes.py."""
    assert len(ROUTE_CATALOG) >= 50, (
        f"Route catalog only has {len(ROUTE_CATALOG)} routes — "
        "the strategy doc targets every @router.get. Add the missing "
        "ones or document why they were intentionally skipped."
    )


def test_route_catalog_includes_health_endpoints():
    """The /healthz/* endpoints are the operator's first stop when
    something breaks. They MUST be in the catalog."""
    urls = {url for _, _, url, _ in ROUTE_CATALOG}
    for must_have in ("/healthz", "/healthz/db"):
        assert must_have in urls, f"missing {must_have} from catalog"
