"""tests/test_migration_076_sale_linked_pedido.py — phase 5 schema migration.

Verifies:
- Schema bumps from 75 → 76 on a fresh DB
- sale.linked_pedido_id column exists
- The timeline service now surfaces sale events (previously stubbed)
- pedido.sales collection works
- apply_sale() accepts and stores linked_pedido_id
- The fulfill endpoint sets linked_pedido_id on every generated sale
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import inspect, text


def test_migration_076_bumps_schema_version(session_factory):
    """Fresh DB starts at 76 (or higher)."""
    with session_factory() as s:
        v = s.execute(text("SELECT value FROM app_meta WHERE key='schema_version'")).scalar()
    assert v is not None
    assert int(v) >= 76


def test_sale_has_linked_pedido_id_column(session_factory):
    """The migration added sale.linked_pedido_id."""
    with session_factory() as s:
        cols = {c["name"] for c in inspect(s.get_bind()).get_columns("sale")}
    assert "linked_pedido_id" in cols


def test_sale_linked_pedido_index_exists(session_factory):
    """Migration also created the index for join performance."""
    with session_factory() as s:
        idx = {i["name"] for i in inspect(s.get_bind()).get_indexes("sale")}
    assert "ix_sale_linked_pedido_id" in idx


def test_apply_sale_sets_linked_pedido_id(session_factory):
    """apply_sale() persists linked_pedido_id when provided."""
    from app.rms.costing import apply_sale
    from app.rms.models import Customer, Pedido, Sale

    with session_factory() as s:
        c = Customer(name="Test Buyer", phone="0990001111")
        s.add(c)
        s.flush()
        cid = c.id

        p = Pedido(customer_id=cid, customer_name="Test Buyer", customer_phone="0990001111",
                   promised_date=datetime.utcnow().date(), status="pending",
                   public_token="test-linked-token-176")
        s.add(p)
        s.flush()
        pid = p.id

        # Pick first product
        from app.rms.models import Product
        prod = s.execute(text("SELECT id FROM product LIMIT 1")).scalar()
        if prod is None:
            # No products in test DB — make one
            from app.rms.models import Product
            prod_row = Product(name="Test Product", sale_price_gs=10000)
            s.add(prod_row)
            s.flush()
            prod = prod_row.id

        result = apply_sale(
            session=s,
            product_id=prod,
            qty=2.0,
            sold_at=datetime.utcnow(),
            customer_id=cid,
            channel="mostrador",
            linked_pedido_id=pid,
        )
        sale_id = result.sale_id
        s.commit()

    # Reload and verify
    with session_factory() as s:
        sale = s.get(Sale, sale_id)
        assert sale.linked_pedido_id == pid


def test_pedido_sales_relationship_returns_linked_sales(qseed, session_factory):
    """After the seed, pedido.sales returns all sales generated by it."""
    from app.rms.models import Pedido, Sale
    from app.seed.kyrian import KYRIAN_PHONE

    qseed("with_kyrian_full")
    with session_factory() as s:
        from app.rms.models import Customer
        c = s.query(Customer).filter_by(phone=KYRIAN_PHONE).one()
        # Find a fulfilled pedido
        p = s.execute(
            __import__("sqlalchemy").select(Pedido)
            .where(Pedido.customer_id == c.id, Pedido.status == "fulfilled")
            .limit(1)
        ).scalar_one()
        pid = p.id
        expected = len([s for s in s.execute(
            __import__("sqlalchemy").select(Sale).where(Sale.linked_pedido_id == pid)
        ).scalars().all()])

        # Use the relationship
        pedidos = s.execute(
            __import__("sqlalchemy").select(Pedido)
            .where(Pedido.id == pid)
            .options(__import__("sqlalchemy").orm.selectinload(Pedido.sales))
        ).scalar_one()
        assert len(pedidos.sales) == expected


def test_timeline_includes_fulfilled_sale_events(qseed, session_factory):
    """After migration 076, the timeline service surfaces sale events
    (it was previously a no-op stub)."""
    qseed("with_kyrian_full")
    from app.rms.models import Customer, Pedido
    from app.seed.kyrian import KYRIAN_PHONE
    from app.services.pedido_history import build_pedido_timeline

    with session_factory() as s:
        c = s.query(Customer).filter_by(phone=KYRIAN_PHONE).one()
        p = s.execute(
            __import__("sqlalchemy").select(Pedido)
            .where(Pedido.customer_id == c.id, Pedido.status == "fulfilled")
            .limit(1)
        ).scalar_one()
        timeline = build_pedido_timeline(s, p)

    fulfilled_events = [e for e in timeline if e.kind == "fulfilled"]
    assert len(fulfilled_events) >= 1
    # First one should be marked as "primer" (matches pedido.fulfilled_sale_id)
    assert any("(primer)" in e.label or e.label.startswith("Venta #") for e in fulfilled_events)


def test_apply_sale_default_linked_pedido_is_none(session_factory):
    """Without the kwarg, linked_pedido_id stays NULL (POS-driven sales)."""
    from app.rms.costing import apply_sale
    from app.rms.models import Customer, Sale

    with session_factory() as s:
        c = Customer(name="POS Customer", phone="0992223333")
        s.add(c)
        s.flush()
        from app.rms.models import Product
        prod = s.execute(text("SELECT id FROM product LIMIT 1")).scalar()
        if prod is None:
            p = Product(name="POS Product", sale_price_gs=5000)
            s.add(p)
            s.flush()
            prod = p.id

        r = apply_sale(
            session=s, product_id=prod, qty=1.0,
            sold_at=datetime.utcnow(), customer_id=c.id,
        )
        s.commit()
        sale = s.get(Sale, r.sale_id)
        assert sale.linked_pedido_id is None
