"""AUTO-GENERATED by scripts/gen_route_smoke.py — do not edit.

Parametrized smoke test for every FastAPI route. Hits each
endpoint with the TestClient, asserts status < 500. Closes
TEST_ARCHITECTURE.md gap G2 (routes without dedicated tests).

Regenerate with:
    python3 scripts/gen_route_smoke.py

Routes covered: 47
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.smoke_generated


# --- GET (41 routes) ---

_ROUTES_GET = [
    ("/", "app"),
    ("/inventario/api/packaging", "app"),
    ("/inventario/export.csv", "app"),
    ("/inventario/api/categories", "app"),
    ("/inventario/{ing_id}/movimientos", "app"),
    ("/inventario/{ing_id}/variantes", "app"),
    ("/inventario/api/search/by-category", "app"),
    ("/inventario/api/search/critical", "app"),
    ("/inventario/api/search/reorder", "app"),
    ("/recetas/{r_id}/crear-producto", "app"),
    ("/recetas/api/{recipe_id}/effective-ingredients", "app"),
    ("/recetas/api/families", "app"),
    ("/recetas/export", "app"),
    ("/suppliers/{s_id}/precios", "app"),
    ("/suppliers/{s_id}/ordenes", "app"),
    ("/productos/api/tags", "app"),
    ("/productos/api/categories", "app"),
    ("/productos/export.csv", "app"),
    ("/ventas/qa", "app"),
    ("/ventas/export.csv", "app"),
    ("/ventas/{sale_id:int}", "app"),
    ("/refunds/{refund_id}", "app"),
    ("/refunds/target/{target_type}/{target_id}", "app"),
    ("/produccion/api/forecast", "app"),
    ("/reportes/consumo", "app"),
    ("/reportes/consumo/csv", "app"),
    ("/bank/export.csv", "app"),
    ("/vs-mercado/evidencia.csv", "app"),
    ("/vs-mercado/evidencia/seed-demo", "app"),
    ("/vs-mercado/{bench_id}/edit", "app"),
    ("/reportes/food-cost-variance", "app"),
    ("/reportes/api/allergen-check", "app"),
    ("/api/insights/", "insights"),
    ("/delivery-zones", "app"),
    ("/auditoria/export.csv", "app"),
    ("/api/settings/pricing-markup/preview", "settings"),
    ("/api/templates/{template_key}", "settings"),
    ("/m/{slug}", "app"),
    ("/pedidos/api/customer-defaults/{customer_id}", "app"),
    ("/pedidos/api/customer/{customer_id}/addresses", "app"),
    ("/pedidos/{pedido_id}/duplicate", "app"),
]


@pytest.mark.parametrize("path,label", _ROUTES_GET)
def test_get_route_does_not_500(client, path, label):
    """GET {path} ({label}) must not 5xx."""
    r = client.get(path)
    assert r.status_code < 500, f"GET {path} ({label}) returned {r.status_code}: {r.text[:200]}"


# --- POST (6 routes) ---

_ROUTES_POST = [
    ("/ventas/{sale_id}/share", "app"),
    ("/wishlist/{item_id}/send-to-shopping-list", "app"),
    ("/bank/{tx_id}/reconcile", "app"),
    ("/bank/{tx_id}/unreconcile", "app"),
    ("/vs-mercado/{bench_id}/save", "app"),
    ("/pedidos/{pedido_id}/duplicate", "app"),
]


@pytest.mark.parametrize("path,label", _ROUTES_POST)
def test_post_route_does_not_500(client, path, label):
    """POST {path} ({label}) must not 5xx."""
    r = client.post(path)
    assert r.status_code < 500, f"POST {path} ({label}) returned {r.status_code}: {r.text[:200]}"
