"""Tier 6.3 (2026-10-01) — /pedidos/{id} linked sales + loyalty impact.

Three small flows added to /pedidos/{id}:
  1. "Ver ficha" button linking to /clientes/{customer_id}.
  2. "Ventas generadas" table listing every Sale whose linked_pedido_id
     points back at this pedido (vs. the legacy single
     fulfilled_sale_id). Migration 076 added the column; the detail
     page now actually renders it.
  3. "Impacto en puntos" card showing earned/redeemed LoyaltyTransaction
     sums for sales generated by this pedido.

Run: cd /opt/data/profiles/ivan/scratch/saskia-app-work && ./.venv/bin/python -m pytest tests/test_pedido_detalle_linked_sales.py -v
"""
from __future__ import annotations

from datetime import datetime, timedelta

import pytest

from app.rms.models import (
    Customer,
    LoyaltyTransaction,
    Pedido,
    PedidoLine,
    Product,
    Sale,
)


@pytest.fixture
def pedido_with_linked_sale(session_factory) -> tuple[int, int, int]:
    """A fulfilled pedido with 1 linked sale + 1 LoyaltyTransaction (earn_sale)."""
    from sqlalchemy.orm import Session
    with session_factory() as s:
        cust = Customer(name="LinkedCust", phone="+595****5001")
        s.add(cust)
        s.flush()
        prod = Product(name="Chipa", sale_price_gs=20_000)
        s.add(prod)
        s.flush()
        pedido = Pedido(
            customer_id=cust.id,
            customer_name="LinkedCust",
            customer_phone="+595****5001",
            status="fulfilled",
            promised_date=datetime(2026, 9, 25).date(),
            channel="mostrador",
            payment_intent="efectivo",
        )
        s.add(pedido)
        s.flush()
        s.add(PedidoLine(
            pedido_id=pedido.id,
            product_id=prod.id,
            qty=2,
            unit_price_gs=20_000,
        ))
        # Linked sale (linked_pedido_id set)
        sale = Sale(
            customer_id=cust.id,
            product_id=prod.id,
            qty=2,
            unit_price_gs=20_000,
            sold_at=datetime(2026, 9, 25, 10, 0),
            channel="mostrador",
            tz="America/Asuncion",
            linked_pedido_id=pedido.id,
        )
        s.add(sale)
        s.flush()
        # Loyalty transaction pointing at the sale
        s.add(LoyaltyTransaction(
            customer_id=cust.id,
            sale_id=sale.id,
            delta=40,  # 2 × 20000 / 1000 = 40 points
            reason="earn_sale",
            recorded_at=datetime(2026, 9, 25, 10, 5),
        ))
        s.commit()
        return pedido.id, cust.id, sale.id


@pytest.fixture
def pedido_no_sales(session_factory) -> int:
    """A pending pedido with no linked sales yet."""
    from sqlalchemy.orm import Session
    with session_factory() as s:
        cust = Customer(name="NoSalesCust", phone="+595****5002")
        s.add(cust)
        s.flush()
        pedido = Pedido(
            customer_id=cust.id,
            customer_name="NoSalesCust",
            status="pending",
            promised_date=datetime.utcnow().date() + timedelta(days=1),
            channel="whatsapp",
            payment_intent="efectivo",
        )
        s.add(pedido)
        s.commit()
        return pedido.id


def test_pedido_detalle_renders_customer_link(client, pedido_with_linked_sale) -> None:
    """/pedidos/{id} shows a 'Ver ficha' link to /clientes/{customer_id}."""
    pedido_id, cust_id, _ = pedido_with_linked_sale
    resp = client.get(f"/pedidos/{pedido_id}")
    assert resp.status_code == 200
    body = resp.text
    assert f'/clientes/{cust_id}' in body, (
        f"Expected /clientes/{cust_id} link in /pedidos/{pedido_id}; "
        f"looking for Tier 6.3 'Ver ficha' button"
    )


def test_pedido_detalle_renders_linked_sales(client, pedido_with_linked_sale) -> None:
    """/pedidos/{id} shows the linked sales (migration 076) when present."""
    pedido_id, _, sale_id = pedido_with_linked_sale
    resp = client.get(f"/pedidos/{pedido_id}")
    assert resp.status_code == 200
    body = resp.text
    # The "Ventas generadas" section must appear
    assert "Ventas generadas" in body, (
        "Expected 'Ventas generadas' section in /pedidos/{id}"
    )
    # The linked sale must appear in the table
    assert f"#{sale_id}" in body or f"#{ sale_id }" in body, (
        f"Expected sale #{sale_id} referenced in linked_sales table"
    )


def test_pedido_detalle_renders_loyalty_impact(client, pedido_with_linked_sale) -> None:
    """/pedidos/{id} shows the loyalty impact (earned/redeemed) summary."""
    pedido_id, _, _ = pedido_with_linked_sale
    resp = client.get(f"/pedidos/{pedido_id}")
    assert resp.status_code == 200
    body = resp.text
    # The "Impacto en puntos" section must appear
    assert "Impacto en puntos" in body, (
        "Expected 'Impacto en puntos' card in /pedidos/{id}"
    )
    # 40 points earned badge
    assert "+40 pts ganados" in body, (
        "Expected '+40 pts ganados' badge for the earn_sale loyalty transaction"
    )


def test_pedido_detalle_no_linked_sales_omits_section(client, pedido_no_sales) -> None:
    """/pedidos/{id} omits the linked_sales section when no sales are linked."""
    resp = client.get(f"/pedidos/{pedido_no_sales}")
    assert resp.status_code == 200
    body = resp.text
    # The "Ventas generadas" section is conditionally rendered — must NOT appear
    assert "Ventas generadas" not in body, (
        "Expected NO 'Ventas generadas' section when pedido has no linked sales"
    )


def test_pedido_detalle_no_loyalty_shows_empty_state(client, pedido_no_sales) -> None:
    """/pedidos/{id} shows the 'no impact yet' empty state when no loyalty txs."""
    resp = client.get(f"/pedidos/{pedido_no_sales}")
    assert resp.status_code == 200
    body = resp.text
    assert "Impacto en puntos" in body, (
        "Card title 'Impacto en puntos' must always render"
    )
    assert "Sin impacto en puntos" in body, (
        "Expected 'Sin impacto en puntos todavía' empty state"
    )


def test_pedido_detalle_does_not_break_when_no_customer(client, session_factory) -> None:
    """/pedidos/{id} renders safely when pedido has no customer (anonymous)."""
    from sqlalchemy.orm import Session
    with session_factory() as s:
        pedido = Pedido(
            customer_id=None,
            customer_name="Anónimo",
            status="pending",
            promised_date=datetime.utcnow().date(),
            channel="mostrador",
            payment_intent="efectivo",
        )
        s.add(pedido)
        s.commit()
        pid = pedido.id

    resp = client.get(f"/pedidos/{pid}")
    assert resp.status_code == 200
    body = resp.text
    # The customer-ficha link is conditional — must NOT appear
    assert "/clientes/" not in body or f"/clientes/None" not in body, (
        "Anonymous pedido must not link to a /clientes/None"
    )


def test_pedido_detalle_redeem_loyalty_subtraction(client, session_factory) -> None:
    """/pedidos/{id} subtracts redeemed points from the net impact."""
    from sqlalchemy.orm import Session
    with session_factory() as s:
        cust = Customer(name="RedeemCust", phone="+595****5003", loyalty_points=120)
        s.add(cust)
        s.flush()
        prod = Product(name="Factura", sale_price_gs=10_000)
        s.add(prod)
        s.flush()
        pedido = Pedido(
            customer_id=cust.id,
            customer_name="RedeemCust",
            status="fulfilled",
            promised_date=datetime(2026, 9, 26).date(),
            channel="mostrador",
            payment_intent="efectivo",
        )
        s.add(pedido)
        s.flush()
        # Two sales: one earns, one redeems
        s_earn = Sale(
            customer_id=cust.id, product_id=prod.id, qty=2,
            unit_price_gs=10_000, sold_at=datetime(2026, 9, 26, 10, 0),
            channel="mostrador", tz="America/Asuncion",
            linked_pedido_id=pedido.id,
        )
        s.add(s_earn)
        s.flush()
        s.add(LoyaltyTransaction(
            customer_id=cust.id, sale_id=s_earn.id, delta=20,
            reason="earn_sale", recorded_at=datetime(2026, 9, 26, 10, 5),
        ))
        s.add(LoyaltyTransaction(
            customer_id=cust.id, sale_id=s_earn.id, delta=-50,
            reason="redeem", recorded_at=datetime(2026, 9, 26, 10, 6),
        ))
        s.commit()
        pid = pedido.id

    resp = client.get(f"/pedidos/{pid}")
    assert resp.status_code == 200
    body = resp.text
    # Both badges (redeem shows absolute amount, no leading minus)
    assert "+20 pts ganados" in body
    assert "50 pts canjeados" in body
    # Net: 20 - 50 = -30
    assert "-30 pts" in body, "Expected net impact of -30 pts"
