"""app/routers/credits.py — photo credits page (CC-BY attribution).

Serves /creditos from a static JSON manifest generated by the asset
pipeline (docs: docs/plans/2026-09-27-image-asset-plan.md). CC0 images
need no attribution; CC-BY requires title/author/license/source links.
"""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, Depends, Request
from fastapi.responses import HTMLResponse

from app.auth import require_login_or_disabled as require_login
from app.services.template_render import render

router = APIRouter(tags=["credits"], dependencies=[Depends(require_login)])

_CREDITS_FILE = Path(__file__).resolve().parents[1] / "static" / "credits.json"


@router.get("/creditos", response_class=HTMLResponse)
def credits_page(request: Request) -> HTMLResponse:
    entries = []
    if _CREDITS_FILE.exists():
        try:
            raw = json.loads(_CREDITS_FILE.read_text(encoding="utf-8"))
            entries = raw if isinstance(raw, list) else raw.get("entries", [])
        except (json.JSONDecodeError, OSError):
            entries = []
    return render(request, "creditos.html", {"entries": entries, "total": len(entries)})
