"""competitor_shoppings.py — shopping competitor seed data.

Sprint 2.4: split from monolithic seed_competitor_prices.py.

58 rows: shopping centers.
"""
COMPETITOR_SEED_SHOPPINGS = [
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Café espresso",
        "cafes",
        "unidad",
        12000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Espresso doble",
        "cafes",
        "unidad",
        17000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        16000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Capuchino",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Capuchino Viennese",
        "cafes",
        "unidad",
        27000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Té",
        "",
        "unidad",
        10000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Té con leche",
        "tes",
        "unidad",
        15000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Chocolate con leche",
        "tes",
        "unidad",
        16000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Croissant",
        "facturas",
        "unidad",
        9000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Medialuna con dulce de leche o guayaba",
        "facturas",
        "unidad",
        9000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Cup cake",
        "",
        "unidad",
        14000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Brownie relleno con dulce de leche",
        "brownies",
        "unidad",
        17000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Cheesecake (porción)",
        "tortas",
        "unidad",
        18000,
        "2026-09-30",
        "https://lavienesa.com.py/web/tarta-de-queso-producto331",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Torta de manzanas (porción)",
        "tortas",
        "unidad",
        20000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Tarta de coco y dulce de leche",
        "tortas",
        "unidad",
        22000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Pastafrola",
        "tortas",
        "unidad",
        16500,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Alfajor Marplatense",
        "cookies",
        "unidad",
        12000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Bomgón artesanal (porción de torta)",
        "tortas",
        "unidad",
        19000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Flan con dulce de leche y chantilly",
        "",
        "unidad",
        22000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Brownie con dulce de leche y helado",
        "brownies",
        "unidad",
        27000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Espresso (corto o jarrito)",
        "cafes",
        "unidad",
        13000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Espresso doble",
        "cafes",
        "unidad",
        20000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Cortado",
        "cafes",
        "unidad",
        14000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        20000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Café con leche XL",
        "",
        "unidad",
        24000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Capuchino",
        "cafes",
        "unidad",
        24000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Café americano",
        "cafes",
        "unidad",
        20000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Té (línea Twinings)",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Medialuna (dulce)",
        "facturas",
        "unidad",
        7000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Alfajor Havanna clásico",
        "cookies",
        "unidad",
        17000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Havannets clásicos (unidad)",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Muffin (arándanos o chocochips)",
        "muffins",
        "unidad",
        12000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Brownie de chocolate",
        "brownies",
        "unidad",
        16000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Cheesecake (porción)",
        "tortas",
        "unidad",
        25000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Pie de limón (porción)",
        "tortas",
        "unidad",
        25000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        17000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café americano",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Brownie",
        "brownies",
        "unidad",
        22000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Almojábana (tradicional colombiano)",
        "",
        "unidad",
        12000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa (tradicional colombiano)",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa de jamón y queso",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Bowl de frutas",
        "",
        "unidad",
        18000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        17000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café americano",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Brownie",
        "brownies",
        "unidad",
        22000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Almojábana (tradicional colombiano)",
        "",
        "unidad",
        12000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa (tradicional colombiano)",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa de jamón y queso",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Bowl de frutas",
        "",
        "unidad",
        18000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Café negro corto (espresso) 300cc",
        "cafes",
        "unidad",
        11000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Café con leche clásico 300cc",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Cortadito 300cc",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Café con leche XXL 500cc",
        "",
        "unidad",
        20000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Té",
        "",
        "unidad",
        11000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Té con leche",
        "tes",
        "unidad",
        13000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Capuccino 300cc",
        "cafes",
        "unidad",
        16000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Chipa piru 100gr",
        "",
        "unidad",
        9000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Mbeju tradicional de almidón",
        "",
        "unidad",
        14000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
]


