"""app/rms/seed_competitor_prices.py — evidencia de precios de competencia (2026-09-30).

Generado desde el repositorio de investigación saskia-market-intel
(/opt/data/work/research-repos/saskia-market-intel) — NO editar a mano:
re-generar desde data/competitor-retail-prices.csv o importar via CSV.

Fuente: cartas online verificadas de 48+ locales PY (corte 2026-09-30).
Idempotente: (competitor_name, product_name, as_of) duplicado se omite.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

COMPETITOR_SEED = [
    (
        "Don Mario Panadería Confitería",
        "panadería/confitería",
        "Asunción (Centro) y Lamb",
        "Caja de facturas x 10 unid",
        "facturas",
        "unidad",
        2700,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Alemana Panadería y Confitería (San Bernardino)",
        "panadería-confitería ale",
        "San Bernardino",
        "Medialunas",
        "facturas",
        "unidad",
        5000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Don Mario Panadería Confitería",
        "panadería/confitería",
        "Asunción (Centro) y Lamb",
        "Medialuna sin relleno",
        "facturas",
        "unidad",
        6000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Panadería Don Mario (fiweex delivery)",
        "Panadería/Confitería",
        "Asunción (referencia de ",
        "Medialuna Sin Relleno",
        "facturas",
        "unidad",
        6000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Don Mario Panadería Confitería",
        "panadería/confitería",
        "Asunción (Centro) y Lamb",
        "Medialuna con dulce de guayaba",
        "facturas",
        "unidad",
        7000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Medialunas Calentitas",
        "panadería/cafetería de m",
        "Asunción (Villa Morra/Li",
        "Medialuna tradicional",
        "facturas",
        "unidad",
        7000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Facturas sin relleno (Confitería)",
        "facturas",
        "unidad",
        7000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Tía Laura Delicias",
        "pastelería/confitería",
        "Asunción (Carmelitas y V",
        "Medialuna sin relleno",
        "facturas",
        "unidad",
        7500,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Tía Laura Delicias",
        "pastelería/confitería",
        "Asunción (Carmelitas y V",
        "Medialuna con dulce de leche",
        "facturas",
        "unidad",
        8500,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Vienesa",
        "confitería/panadería/res",
        "Asunción y Gran Asunción",
        "Croissant",
        "facturas",
        "unidad",
        9000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu",
        "panadería artesanal/cafe",
        "Asunción (Las Mercedes y",
        "Medialuna de manteca",
        "facturas",
        "unidad",
        10000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Medialunas Calentitas",
        "cafetería",
        "Asunción",
        "Medialuna rellena clásica",
        "facturas",
        "unidad",
        10000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Medialunas Calentitas",
        "panadería/cafetería de m",
        "Asunción (Villa Morra/Li",
        "Medialuna rellena premium (Nutella/Oreo/Luna Rocher)",
        "facturas",
        "unidad",
        13000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu Gastro Mercado (Ykua Satí)",
        "cafetería de mercado/gas",
        "Asunción",
        "Croissant",
        "facturas",
        "unidad",
        13000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "panadería-cafetería-bist",
        "Encarnación",
        "Torta (porción, dulce)",
        "tortas",
        "unidad",
        5000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Alberdin",
        "confitería/catering",
        "Asunción (Quinta Avda, C",
        "Pastafrola cuadrada (porción)",
        "tortas",
        "unidad",
        9000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Panadería Don Mario (fiweex delivery)",
        "Panadería/Confitería",
        "Asunción (referencia de ",
        "Tarta de Cebolla y queso (En porción)",
        "tortas",
        "unidad",
        9000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Vienesa",
        "confitería/panadería/res",
        "Asunción y Gran Asunción",
        "Cheesecake (postre)",
        "tortas",
        "unidad",
        12000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Panadería Don Mario (fiweex delivery)",
        "Panadería/Confitería",
        "Asunción (referencia de ",
        "Chocotorta",
        "tortas",
        "unidad",
        12000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Pastafrola (Panificados Dulces)",
        "tortas",
        "unidad",
        15000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Tía Laura Delicias",
        "pastelería/confitería",
        "Asunción (Carmelitas y V",
        "Porción pastafrola",
        "tortas",
        "unidad",
        17000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "panadería-cafetería-bist",
        "Encarnación",
        "Cheesecake de Oreo (porción)",
        "tortas",
        "unidad",
        20000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Café Martínez (Centro + cadena PY)",
        "cafetería premium (caden",
        "Asunción",
        "Porción de torta",
        "tortas",
        "unidad",
        22000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu",
        "panadería artesanal/cafe",
        "Asunción (Las Mercedes y",
        "Tarta de manzana",
        "tortas",
        "unidad",
        25000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Panadería Don Mario (fiweex delivery)",
        "Panadería/Confitería",
        "Asunción (referencia de ",
        "Torta de yogurth c/ naranja",
        "tortas",
        "unidad",
        27000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Cafetería Panadería San Telmo",
        "panadería-cafetería-rest",
        "Ciudad del Este",
        "Tarta de frutilla",
        "tortas",
        "unidad",
        28000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Panadería La Negrita",
        "Panadería",
        "Coronel Oviedo",
        "Mini torta especial x unid.",
        "tortas",
        "unidad",
        38000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Supermercado Gran Vía (panadería y confitería)",
        "supermercado con panader",
        "Ciudad del Este",
        "Torta Gran Vía (unidad)",
        "tortas",
        "unidad",
        56000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Tía Laura Delicias",
        "pastelería/confitería",
        "Asunción (Carmelitas y V",
        "Torta chocolate tradicional entera",
        "tortas",
        "unidad",
        89500,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Tía Laura Delicias",
        "pastelería/confitería",
        "Asunción (Carmelitas y V",
        "Torta cookies & cream entera",
        "tortas",
        "unidad",
        98900,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Red Sagrados",
        "pastelería online",
        "Asunción (delivery)",
        "Brownie personal",
        "brownies",
        "unidad",
        8000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Alfa-brownie (Confitería)",
        "brownies",
        "unidad",
        10000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Vienesa (Legión Civil Extranjera / Palmeras)",
        "confitería-cafetería",
        "Asunción",
        "Brownie clásico",
        "brownies",
        "unidad",
        14000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Tía Laura Delicias",
        "pastelería/confitería",
        "Asunción (Carmelitas y V",
        "Brownie",
        "brownies",
        "unidad",
        15500,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Vienesa",
        "confitería/panadería/res",
        "Asunción y Gran Asunción",
        "Brownie clásico",
        "brownies",
        "unidad",
        20000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu",
        "panadería artesanal/cafe",
        "Asunción (Las Mercedes y",
        "Brownie con helado o chantilly (postre)",
        "brownies",
        "unidad",
        22000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Havanna (Shopping del Sol)",
        "cafetería/alfajores (fra",
        "Asunción",
        "Porción torta brownie",
        "brownies",
        "unidad",
        25000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu",
        "panadería artesanal/cafe",
        "Asunción (Las Mercedes y",
        "Brownie con mousseline de mburukuja",
        "brownies",
        "unidad",
        29000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Casa Rica (cadena supermercado/gourmet)",
        "panadería-supermercado",
        "Asunción + Gran ASU",
        "Muffin de vainilla",
        "muffins",
        "unidad",
        4200,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "panadería-cafetería-bist",
        "Encarnación",
        "Muffin de banana y avena",
        "muffins",
        "unidad",
        5000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "panadería-cafetería-bist",
        "Encarnación",
        "Muffin chocolate",
        "muffins",
        "unidad",
        5000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Muffin de Vainilla (Confitería)",
        "muffins",
        "unidad",
        5000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Muffin Vainilla con chips (Confitería)",
        "muffins",
        "unidad",
        5000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Havanna (Shopping del Sol)",
        "cafetería/alfajores (fra",
        "Asunción",
        "Alfajor clásico de chocolate (unidad)",
        "cookies",
        "unidad",
        800,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Alberdin",
        "confitería/catering",
        "Asunción (Quinta Avda, C",
        "Alfajor de maicena grande",
        "cookies",
        "unidad",
        7000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Cookies Maní (Confitería)",
        "cookies",
        "unidad",
        8000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Bistró del Centro",
        "Panadería/Cafetería",
        "Encarnación",
        "Alfajor Marplatense (Confitería)",
        "cookies",
        "unidad",
        10000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Vienesa (cadena, 9 sucursales; matriz Oliva, Asunción)",
        "cafetería",
        "Asunción (cadena naciona",
        "Alfajor maicena grande",
        "cookies",
        "unidad",
        12000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Havanna (Shopping del Sol)",
        "cadena cafetería-alfajor",
        "Asunción (referencia de ",
        "Alfajor de cacao 70% x9",
        "cookies",
        "unidad",
        15000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Casa Rica (cadena supermercado/gourmet)",
        "panadería-supermercado",
        "Asunción + Gran ASU",
        "Pan baguette mediano",
        "panes",
        "unidad",
        6500,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Casa Rica (panificación propia)",
        "Supermercado/cadena",
        "Cadena nacional (online)",
        "Pan baguette campestre x un",
        "panes",
        "unidad",
        8700,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Panadería Don Mario (fiweex delivery)",
        "Panadería/Confitería",
        "Asunción (referencia de ",
        "Pan de Molde (Con sal)",
        "panes",
        "unidad",
        10000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Areté Supermercados",
        "Supermercado/cadena",
        "Cadena nacional (online)",
        "Pan integral Bimbo 420gr",
        "panes",
        "unidad",
        12200,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Supermercados Stock",
        "Supermercado/cadena",
        "Cadena nacional (sucursa",
        "Pan integral El Germano 400gr",
        "panes",
        "unidad",
        13300,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "La Vienesa (cadena, 9 sucursales; matriz Oliva, Asunción)",
        "cafetería",
        "Asunción (cadena naciona",
        "Tostado J&Q pan blanco/integral",
        "panes",
        "unidad",
        16000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Cafetería Panadería San Telmo",
        "panadería-cafetería-rest",
        "Ciudad del Este",
        "Café filtrado",
        "cafes",
        "unidad",
        6000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Cafetería Panadería San Telmo",
        "panadería-cafetería-rest",
        "Ciudad del Este",
        "Café americano Nespresso",
        "cafes",
        "unidad",
        14000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Juan Valdez Café (Shopping Mariscal López)",
        "cafetería premium (caden",
        "Asunción",
        "Espresso Doble",
        "cafes",
        "unidad",
        15000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "XOXO Café & Restó",
        "cafetería",
        "Encarnación",
        "Americano",
        "cafes",
        "unidad",
        15000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "San Telmo Resto-Café",
        "cafetería",
        "Ciudad del Este",
        "Café Expreso Doble 60ml",
        "cafes",
        "unidad",
        16000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu Gastro Mercado (Ykua Satí)",
        "cafetería de mercado/gas",
        "Asunción",
        "Cortado/Doble",
        "cafes",
        "unidad",
        17000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu Panadería y Cocina Artesanal (Las Mercedes / Ycua Sati)",
        "cafetería",
        "Asunción",
        "Espresso",
        "cafes",
        "unidad",
        17000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "XOXO Café & Restó",
        "cafetería",
        "Encarnación",
        "Espresso martini",
        "cafes",
        "unidad",
        18000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Cafetería Panadería San Telmo",
        "panadería-cafetería-rest",
        "Ciudad del Este",
        "Café latte caliente",
        "cafes",
        "unidad",
        20000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Medialunas Calentitas",
        "cafetería",
        "Asunción",
        "Capuchino",
        "cafes",
        "unidad",
        20000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Juan Valdez Café (Shopping Mariscal López)",
        "cafetería premium (caden",
        "Asunción",
        "Latte Frío",
        "cafes",
        "unidad",
        22000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu Panadería y Cocina Artesanal",
        "panadería artesanal-cafe",
        "Luque",
        "Capuchino",
        "cafes",
        "unidad",
        24000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "San Telmo Resto-Café",
        "cafetería",
        "Ciudad del Este",
        "Capuccino frío",
        "cafes",
        "unidad",
        24000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Nina Café",
        "cafetería",
        "Dr. Juan Eulogio Estigar",
        "Iced Latte",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Molas 1901",
        "cafetería-restaurante",
        "Asunción",
        "Té verde con sabor a vainilla",
        "tes",
        "unidad",
        8000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Naéu (San Lorenzo Shopping)",
        "panadería-cafetería",
        "San Lorenzo",
        "Cocido negro 300cc",
        "tes",
        "unidad",
        10000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Naéu (San Lorenzo Shopping)",
        "panadería-cafetería",
        "San Lorenzo",
        "Té con leche",
        "tes",
        "unidad",
        12000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Naéu (Villa Morra Shopping)",
        "panadería-cafetería",
        "Asunción",
        "Cocido con leche 300cc",
        "tes",
        "unidad",
        13000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu Panadería y Cocina Artesanal (Las Mercedes / Ycua Sati)",
        "cafetería",
        "Asunción",
        "Cocido negro",
        "tes",
        "unidad",
        14000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Naéu (San Lorenzo Shopping)",
        "panadería-cafetería",
        "San Lorenzo",
        "Cocido negro XXL 500cc",
        "tes",
        "unidad",
        15000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Karu Gastro Mercado (Ykua Satí)",
        "cafetería de mercado/gas",
        "Asunción",
        "Cocido con leche",
        "tes",
        "unidad",
        15000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Naéu (Villa Morra Shopping)",
        "panadería-cafetería",
        "Asunción",
        "Cocido negro XXL 500cc",
        "tes",
        "unidad",
        16000,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Stroopwafels IMPORTADOS (Yaxa/Daelmans) — piso de importació",
        "producto importado",
        "online nacional",
        "Daelmans 24-pack",
        "stroopwafels",
        "unidad",
        14929,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Importado (Yaxa)",
        "importado",
        "online",
        "Daelmans 24pack",
        "stroopwafels",
        "unidad",
        14929,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Stroopwafels IMPORTADOS (Yaxa/Daelmans) — piso de importació",
        "producto importado",
        "online nacional",
        "Daelmans 8 unidades",
        "stroopwafels",
        "unidad",
        20328,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Importado (Yaxa)",
        "importado",
        "online",
        "Daelmans 8und",
        "stroopwafels",
        "unidad",
        20328,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Stroopwafels IMPORTADOS (Yaxa/Daelmans) — piso de importació",
        "producto importado",
        "online nacional",
        "Daelmans caja hexagonal 6 u",
        "stroopwafels",
        "unidad",
        26291,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Importado (Yaxa)",
        "importado",
        "online",
        "Daelmans hexa 6u",
        "stroopwafels",
        "unidad",
        26291,
        "2026-09-30",
        "repo market-intel/",
    ),
    (
        "Yaxa import",
        "importado",
        "online",
        "Daelmans 8und (importado, agotado)",
        "stroopwafels",
        "unidad",
        20328,
        "2026-09-30",
        "paraguay.yaxa.co",
    ),
    (
        "Yaxa import",
        "importado",
        "online",
        "Daelmans hexa 6u (importado, agotado)",
        "stroopwafels",
        "unidad",
        26291,
        "2026-09-30",
        "paraguay.yaxa.co",
    ),
    (
        "Yaxa import",
        "importado",
        "online",
        "Daelmans 24pack (importado, agotado)",
        "stroopwafels",
        "unidad",
        14929,
        "2026-09-30",
        "paraguay.yaxa.co",
    ),
]


# --- Shopping food-court ASU (Paseo La Galería / del Sol) — lane shoppings 2026-09-30 ---
COMPETITOR_SEED_SHOPPINGS = [
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Café espresso",
        "cafes",
        "unidad",
        12000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Espresso doble",
        "cafes",
        "unidad",
        17000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        16000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Capuchino",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Capuchino Viennese",
        "cafes",
        "unidad",
        27000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Té",
        "",
        "unidad",
        10000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Té con leche",
        "tes",
        "unidad",
        15000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Chocolate con leche",
        "tes",
        "unidad",
        16000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Croissant",
        "facturas",
        "unidad",
        9000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Medialuna con dulce de leche o guayaba",
        "facturas",
        "unidad",
        9000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Cup cake",
        "",
        "unidad",
        14000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Brownie relleno con dulce de leche",
        "brownies",
        "unidad",
        17000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Cheesecake (porción)",
        "tortas",
        "unidad",
        18000,
        "2026-09-30",
        "https://lavienesa.com.py/web/tarta-de-queso-producto331",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Torta de manzanas (porción)",
        "tortas",
        "unidad",
        20000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Tarta de coco y dulce de leche",
        "tortas",
        "unidad",
        22000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Pastafrola",
        "tortas",
        "unidad",
        16500,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Alfajor Marplatense",
        "cookies",
        "unidad",
        12000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Bomgón artesanal (porción de torta)",
        "tortas",
        "unidad",
        19000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Flan con dulce de leche y chantilly",
        "",
        "unidad",
        22000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "La Vienesa",
        "cafetería-shopping",
        "Asunción",
        "Brownie con dulce de leche y helado",
        "brownies",
        "unidad",
        27000,
        "2026-09-30",
        "https://lavienesa.com.py/menu.pdf",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Espresso (corto o jarrito)",
        "cafes",
        "unidad",
        13000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Espresso doble",
        "cafes",
        "unidad",
        20000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Cortado",
        "cafes",
        "unidad",
        14000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        20000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Café con leche XL",
        "",
        "unidad",
        24000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Capuchino",
        "cafes",
        "unidad",
        24000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Café americano",
        "cafes",
        "unidad",
        20000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Té (línea Twinings)",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Medialuna (dulce)",
        "facturas",
        "unidad",
        7000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Alfajor Havanna clásico",
        "cookies",
        "unidad",
        17000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Havannets clásicos (unidad)",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Muffin (arándanos o chocochips)",
        "muffins",
        "unidad",
        12000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Brownie de chocolate",
        "brownies",
        "unidad",
        16000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Cheesecake (porción)",
        "tortas",
        "unidad",
        25000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Havanna",
        "cafetería-shopping",
        "Asunción",
        "Pie de limón (porción)",
        "tortas",
        "unidad",
        25000,
        "2026-09-30",
        "https://fiweex.com/preview_pdf/729",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        17000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café americano",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Brownie",
        "brownies",
        "unidad",
        22000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Almojábana (tradicional colombiano)",
        "",
        "unidad",
        12000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa (tradicional colombiano)",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa de jamón y queso",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Bowl de frutas",
        "",
        "unidad",
        18000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café con leche",
        "",
        "unidad",
        17000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Café americano",
        "cafes",
        "unidad",
        25000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Brownie",
        "brownies",
        "unidad",
        22000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Almojábana (tradicional colombiano)",
        "",
        "unidad",
        12000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa (tradicional colombiano)",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Arepa de jamón y queso",
        "",
        "unidad",
        15000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Juan Valdez Café",
        "cafetería-shopping",
        "Asunción",
        "Bowl de frutas",
        "",
        "unidad",
        18000,
        "2026-09-30",
        "https://juanvaldezcafe.com.py/collections/all",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Café negro corto (espresso) 300cc",
        "cafes",
        "unidad",
        11000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Café con leche clásico 300cc",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Cortadito 300cc",
        "",
        "unidad",
        13000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Café con leche XXL 500cc",
        "",
        "unidad",
        20000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Té",
        "",
        "unidad",
        11000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Té con leche",
        "tes",
        "unidad",
        13000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Capuccino 300cc",
        "cafes",
        "unidad",
        16000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Chipa piru 100gr",
        "",
        "unidad",
        9000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
    (
        "Naéu (Ña Eustaquia)",
        "cafetería-shopping",
        "Asunción",
        "Mbeju tradicional de almidón",
        "",
        "unidad",
        14000,
        "2026-09-30",
        "https://naeu.com.py/sol.pdf",
    ),
]


def seed_competitor_prices(session: "Session") -> "tuple[int, int]":
    """Inserta observaciones si no existen (idempotente). Devuelve (nuevas, omitidas)."""
    from datetime import date

    from sqlalchemy import select

    from app.rms.models import CompetitorPriceObservation

    existing = set(
        session.execute(
            select(
                CompetitorPriceObservation.competitor_name,
                CompetitorPriceObservation.product_name,
                CompetitorPriceObservation.as_of,
            )
        ).all()
    )
    added = skipped = 0
    for comp, ctype, city, item, fam, unit, price, asof, fuente in (
        COMPETITOR_SEED + COMPETITOR_SEED_SHOPPINGS
    ):
        as_of = date.fromisoformat(asof)
        if (comp, item, as_of) in existing:
            skipped += 1
            continue
        session.add(
            CompetitorPriceObservation(
                competitor_name=comp,
                competitor_type=ctype,
                city=city,
                product_name=item,
                family=fam,
                unit=unit,
                price_gs=price,
                as_of=as_of,
                source=fuente,
            )
        )
        added += 1
    session.commit()
    return added, skipped
