#!/usr/bin/env python3
"""scripts/gen_route_smoke.py — generate a smoke test for every FastAPI route.

Closes TEST_ARCHITECTURE.md gap G2 (routes without dedicated tests).

Strategy: introspect the live FastAPI app via app.routes, filter to
GET/POST/PUT/DELETE/PATCH endpoints, skip already-covered routes, and
emit a parametrized test file that hits each one with the TestClient.

Usage:
    python3 scripts/gen_route_smoke.py                 # writes test_route_smoke_generated.py
    python3 scripts/gen_route_smoke.py --dry-run       # prints routes, no write
    python3 scripts/gen_route_smoke.py --router inventory  # only inventory routes
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).parent.parent
TESTS_DIR = REPO_ROOT / "tests"
OUTPUT_FILE = TESTS_DIR / "test_route_smoke_generated.py"


# Routes that should never be smoke-tested (infrastructure, dev tools,
# static assets, OAuth callbacks).
SKIP_PATH_PATTERNS = [
    re.compile(r"^/static/"),  # static asset mount
    re.compile(r"^/favicon"),  # favicons
    re.compile(r"^/docs/"),  # FastAPI auto-docs
    re.compile(r"^/api/openapi"),  # schema endpoint
    re.compile(r"^/api/docs"),  # swagger UI
    re.compile(r"/oauth2-redirect"),  # OAuth callbacks
    re.compile(r"^/_"),  # private/internal
]

# Routes that need a path param to test (skip the bare GET, generate
# /resource/{id} GET with a placeholder id that we expect to 404/422).
PATH_PARAM_PLACEHOLDERS = {
    "id": "999999",  # high id usually doesn't exist; assert 404 or 422
    "pk": "999999",
    "slug": "x",  # safe placeholder
}


def _setup_import_path() -> None:
    """Make `app` importable, fake pytest presence for the auth-bypass check."""
    sys.path.insert(0, str(REPO_ROOT))
    sys.modules.setdefault("pytest", __import__("pytest"))
    os.environ.setdefault("SASKIA_TEST_AUTH_DISABLED", "1")


def collect_routes(app) -> list[tuple[str, str, str]]:
    """Return [(method, path, router_label)] for every smoke-testable endpoint.

    `router_label` is the first tag the route was given (e.g. "ventas"), or
    "app" if untagged.
    """
    out: list[tuple[str, str, str]] = []
    for r in app.routes:
        if not hasattr(r, "methods") or not hasattr(r, "path"):
            continue
        # Skip HEAD (tested via GET)
        for m in sorted(r.methods - {"HEAD"}):
            path = r.path
            # Skip infrastructure paths
            if any(p.match(path) for p in SKIP_PATH_PATTERNS):
                continue
            # Skip the auth-bypass test endpoint itself
            if path == "/_test_auth_bypass":
                continue
            tag = (r.tags or ["app"])[0] if hasattr(r, "tags") else "app"
            out.append((m, path, tag))
    return out


def existing_test_paths() -> set[str]:
    """Read existing test files, extract every HTTP path they reference.

    Catches: 'route'/route/path', "/ventas", "/api/X", f"/y/{id}", etc.
    """
    paths: set[str] = set()
    # Patterns that look like a path in a test file
    re_quoted = re.compile(r"""['"](/[a-zA-Z0-9_/{}\-]+)['"]""")
    re_fstring = re.compile(r"""f['"](/[a-zA-Z0-9_/{}\-]+)['"]""")
    for tf in TESTS_DIR.rglob("test_*.py"):
        text = tf.read_text()
        for m in re_quoted.findall(text):
            paths.add(m)
        for m in re_fstring.findall(text):
            paths.add(m)
    return paths


def is_already_covered(method: str, path: str, covered: set[str]) -> bool:
    """True if a test already references this route by a quoted/fstring'd string."""
    # Direct match (e.g., "/ventas")
    if path in covered:
        return True
    # Path with placeholder (e.g., "/ventas/{id}")
    placeholder = path
    for k, v in PATH_PARAM_PLACEHOLDERS.items():
        placeholder = placeholder.replace("{" + k + "}", v)
    if placeholder in covered:
        return True
    return False


def render_test_file(
    routes: Iterable[tuple[str, str, str]],
    *,
    output: Path,
) -> None:
    """Write a pytest file with one parametrized test per route."""
    lines: list[str] = []
    lines.append('"""AUTO-GENERATED by scripts/gen_route_smoke.py — do not edit.')
    lines.append("")
    lines.append("Parametrized smoke test for every FastAPI route. Hits each")
    lines.append("endpoint with the TestClient, asserts status < 500. Closes")
    lines.append("TEST_ARCHITECTURE.md gap G2 (routes without dedicated tests).")
    lines.append("")
    lines.append("Regenerate with:")
    lines.append("    python3 scripts/gen_route_smoke.py")
    lines.append("")
    lines.append(f"Routes covered: {sum(1 for _ in routes)}")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    lines.append("pytestmark = pytest.mark.smoke_generated")
    lines.append("")
    lines.append("")

    # Group routes by method for readability
    by_method: dict[str, list[tuple[str, str]]] = {}
    for m, p, t in routes:
        by_method.setdefault(m, []).append((p, t))

    for method in ["GET", "POST", "PUT", "PATCH", "DELETE"]:
        items = by_method.get(method, [])
        if not items:
            continue
        lines.append(f"# --- {method} ({len(items)} routes) ---")
        lines.append("")
        # Build the parametrize list
        param_cases = [(p, t) for p, t in items]
        lines.append(f"_ROUTES_{method} = {param_cases!r}")
        lines.append("")
        lines.append(f'@pytest.mark.parametrize("path,label", _ROUTES_{method})')
        lines.append(f"def test_{method.lower()}_route_does_not_500(client, path, label):")
        lines.append(f'    """{method} {{path}} ({{label}}) must not 5xx."""')
        lines.append(f"    r = client.{method.lower()}(path)")
        lines.append("    assert r.status_code < 500, (")
        lines.append(
            f'        f"{method} {{path}} ({{label}}) returned {{r.status_code}}: {{r.text[:200]}}"'
        )
        lines.append("    )")
        lines.append("")

    output.write_text("\n".join(lines))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true", help="print routes, no write")
    p.add_argument("--router", help="only include routes starting with /<router>")
    p.add_argument(
        "--include-covered",
        action="store_true",
        help="include routes already covered by other tests (use for debugging)",
    )
    args = p.parse_args()

    _setup_import_path()

    # Import the app
    from app.rms.main import app

    routes = collect_routes(app)
    print(f"Total FastAPI routes: {len(routes)}")

    # Filter by router
    if args.router:
        routes = [(m, p, t) for (m, p, t) in routes if p.startswith(f"/{args.router}")]
        print(f"After --router={args.router}: {len(routes)}")

    # Skip already-covered (unless told otherwise)
    if not args.include_covered:
        covered = existing_test_paths()
        before = len(routes)
        routes = [(m, p, t) for (m, p, t) in routes if not is_already_covered(m, p, covered)]
        print(f"After skip-already-covered: {len(routes)} (filtered {before - len(routes)})")

    if args.dry_run:
        for m, p, t in routes:
            print(f"  {m:6} {p:60} [{t}]")
        return 0

    render_test_file(routes, output=OUTPUT_FILE)
    print(f"Wrote {OUTPUT_FILE.relative_to(REPO_ROOT)} ({len(routes)} routes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
