#!/usr/bin/env python3
"""
Save SASKIA_USER_PASSWORD to BWS without it appearing as a string literal.

Usage:
    1. Paste the password into /tmp/saskia_pwd.txt
       (NEVER include it in chat, NEVER commit it, NEVER echo it.)
    2. chmod 600 /tmp/saskia_pwd.txt
    3. python3 scripts/save_saskia_user_password.py
    4. shred -u /tmp/saskia_pwd.txt

Mirrors scripts/save_saskia_db_url.py — same Pattern 5 (file-based).
"""

from __future__ import annotations

import sys
import uuid
from pathlib import Path

sys.path.insert(0, "/opt/data/.venv/lib/python3.11/site-packages")

from bitwarden_sdk import BitwardenClient, ClientSettings, DeviceType  # noqa: E402

PWD_FILE = Path("/tmp/saskia_pwd.txt")
BWS_TOKEN_PATH = Path("/opt/data/.hermes/inbox/bws-token.secret")
ORG_ID_PATH = Path("/opt/data/.hermes/inbox/org-id.txt")
PROJECT_ID_PATH = Path("/opt/data/.hermes/inbox/bws-project-id-hermes.txt")
SECRET_NAME = "SASKIA_USER_PASSWORD"
SECRET_NOTE = (
    "Saskia RMS login password (saskia@paragu-ai.com). Auto-generated by Supabase 2026-09-02."
)


def main() -> int:
    if not PWD_FILE.exists():
        print(f"ERROR: {PWD_FILE} does not exist.", file=sys.stderr)
        print(f"  Create it: nano {PWD_FILE}", file=sys.stderr)
        print("  Paste the password on a single line.", file=sys.stderr)
        print(f"  chmod 600 {PWD_FILE}", file=sys.stderr)
        return 2

    mode = PWD_FILE.stat().st_mode & 0o777
    if mode & 0o077:
        print(f"WARNING: {PWD_FILE} has permissive mode {oct(mode)}", file=sys.stderr)

    pwd = PWD_FILE.read_text().strip()
    if len(pwd) < 8:
        print(
            f"ERROR: password too short ({len(pwd)} chars). Supabase requires 8+.", file=sys.stderr
        )
        return 2

    token = BWS_TOKEN_PATH.read_text().strip()
    org_id = ORG_ID_PATH.read_text().strip()
    project_id = PROJECT_ID_PATH.read_text().strip()
    c = BitwardenClient(
        ClientSettings(
            api_url="https://api.bitwarden.com",
            identity_url="https://identity.bitwarden.com",
            user_agent="saskia-deploy/2",
            device_type=DeviceType.SERVER,
        )
    )
    c.auth().login_access_token(token, None)

    # Note: BWS SDK requires `key` (not `name`) and project_ids as a list
    # for create() to succeed (otherwise 404 on a valid org).
    result = c.secrets().create(
        organization_id=uuid.UUID(org_id),
        key=SECRET_NAME,
        value=pwd,
        note=SECRET_NOTE,
        project_ids=[uuid.UUID(project_id)],
    )

    new_id = result.data.id
    new_id_str = new_id.hex if hasattr(new_id, "hex") else str(new_id)
    print(f"saved: {new_id_str}")
    print(f"# {SECRET_NAME} stored. Password was {len(pwd)} chars (not echoed).")
    print(f"# DELETE THE INPUT FILE: shred -u {PWD_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
